name: .NET CI/CD for WPF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest # build on windows machine

    steps:
    - name: Download repo code
      uses: actions/checkout@v4

    - name: Install .NET environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: NuGet Restore
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Run xUnit tests
      run: dotnet test --no-build --verbosity normal